// Indian cities coordinates for the platform
export const INDIAN_CITIES: Record<string, { lat: number; lng: number; state: string }> = {
    'Delhi': { lat: 28.6139, lng: 77.209, state: 'Delhi' },
    'Mumbai': { lat: 19.076, lng: 72.8777, state: 'Maharashtra' },
    'Bangalore': { lat: 12.9716, lng: 77.5946, state: 'Karnataka' },
    'Chennai': { lat: 13.0827, lng: 80.2707, state: 'Tamil Nadu' },
    'Kolkata': { lat: 22.5726, lng: 88.3639, state: 'West Bengal' },
    'Hyderabad': { lat: 17.385, lng: 78.4867, state: 'Telangana' },
    'Pune': { lat: 18.5204, lng: 73.8567, state: 'Maharashtra' },
    'Ahmedabad': { lat: 23.0225, lng: 72.5714, state: 'Gujarat' },
    'Jaipur': { lat: 26.9124, lng: 75.7873, state: 'Rajasthan' },
    'Lucknow': { lat: 26.8467, lng: 80.9462, state: 'Uttar Pradesh' },
    'Chandigarh': { lat: 30.7333, lng: 76.7794, state: 'Chandigarh' },
    'Nagpur': { lat: 21.1458, lng: 79.0882, state: 'Maharashtra' },
    'Indore': { lat: 22.7196, lng: 75.8577, state: 'Madhya Pradesh' },
    'Bhopal': { lat: 23.2599, lng: 77.4126, state: 'Madhya Pradesh' },
    'Surat': { lat: 21.1702, lng: 72.8311, state: 'Gujarat' },
};

export const EMISSION_ZONES = [
    {
        name: 'Delhi Green Belt - Yamuna Biodiversity Park',
        type: 'green',
        centerLat: 28.7041,
        centerLng: 77.1025,
        radiusKm: 3,
        restrictions: JSON.stringify({ maxSpeed: 30, dieselBan: true, timeRestriction: '6AM-10PM' }),
    },
    {
        name: 'Mumbai Coastal Regulation Zone',
        type: 'restricted',
        centerLat: 19.0760,
        centerLng: 72.8777,
        radiusKm: 2.5,
        restrictions: JSON.stringify({ maxSpeed: 20, heavyVehicleBan: true }),
    },
    {
        name: 'Bangalore Cubbon Park Zone',
        type: 'green',
        centerLat: 12.9763,
        centerLng: 77.5929,
        radiusKm: 1.5,
        restrictions: JSON.stringify({ maxSpeed: 20, dieselBan: true, honkingBan: true }),
    },
    {
        name: 'Chennai Marina Zone',
        type: 'green',
        centerLat: 13.0500,
        centerLng: 80.2824,
        radiusKm: 2,
        restrictions: JSON.stringify({ maxSpeed: 25, dieselBan: true }),
    },
    {
        name: 'Delhi ITO Restricted Zone',
        type: 'restricted',
        centerLat: 28.6289,
        centerLng: 77.2405,
        radiusKm: 1.5,
        restrictions: JSON.stringify({ oddEvenRule: true, truckBan: '7AM-11PM' }),
    },
    {
        name: 'Kolkata Industrial Belt',
        type: 'industrial',
        centerLat: 22.5200,
        centerLng: 88.3400,
        radiusKm: 4,
        restrictions: JSON.stringify({ emissionCheck: true, speedLimit: 40 }),
    },
    {
        name: 'Hyderabad Hussain Sagar Zone',
        type: 'green',
        centerLat: 17.4239,
        centerLng: 78.4738,
        radiusKm: 1.8,
        restrictions: JSON.stringify({ dieselBan: true, maxSpeed: 20 }),
    },
    {
        name: 'Pune Sinhagad Road Eco-Zone',
        type: 'green',
        centerLat: 18.4800,
        centerLng: 73.8300,
        radiusKm: 2,
        restrictions: JSON.stringify({ maxSpeed: 25, heavyVehicleBan: true }),
    },
];

export const SEED_VEHICLES = [
    { name: 'GreenHaul Alpha', type: 'truck', licensePlate: 'DL-01-AB-1234', fuelType: 'diesel', bs6Compliant: true, currentLat: 28.6139, currentLng: 77.209, status: 'active' },
    { name: 'EcoFreight Beta', type: 'truck', licensePlate: 'MH-02-CD-5678', fuelType: 'cng', bs6Compliant: true, currentLat: 19.076, currentLng: 72.8777, status: 'active' },
    { name: 'CarbonLite Gamma', type: 'van', licensePlate: 'KA-03-EF-9012', fuelType: 'electric', bs6Compliant: true, currentLat: 12.9716, currentLng: 77.5946, status: 'active' },
    { name: 'SwiftCarry Delta', type: 'truck', licensePlate: 'TN-04-GH-3456', fuelType: 'diesel', bs6Compliant: true, currentLat: 13.0827, currentLng: 80.2707, status: 'idle' },
    { name: 'GreenPath Epsilon', type: 'van', licensePlate: 'WB-05-IJ-7890', fuelType: 'cng', bs6Compliant: true, currentLat: 22.5726, currentLng: 88.3639, status: 'active' },
    { name: 'EcoTransit Zeta', type: 'tanker', licensePlate: 'TS-06-KL-2345', fuelType: 'diesel', bs6Compliant: false, currentLat: 17.385, currentLng: 78.4867, status: 'active' },
    { name: 'CleanMile Eta', type: 'truck', licensePlate: 'MH-07-MN-6789', fuelType: 'electric', bs6Compliant: true, currentLat: 18.5204, currentLng: 73.8567, status: 'maintenance' },
    { name: 'LowCarbon Theta', type: 'van', licensePlate: 'GJ-08-OP-0123', fuelType: 'cng', bs6Compliant: true, currentLat: 23.0225, currentLng: 72.5714, status: 'active' },
    { name: 'GreenWheels Iota', type: 'truck', licensePlate: 'RJ-09-QR-4567', fuelType: 'diesel', bs6Compliant: true, currentLat: 26.9124, currentLng: 75.7873, status: 'active' },
    { name: 'EcoFleet Kappa', type: 'tanker', licensePlate: 'UP-10-ST-8901', fuelType: 'diesel', bs6Compliant: false, currentLat: 26.8467, currentLng: 80.9462, status: 'idle' },
];
